#!/usr/bin/env python3

'''
Print the pair (edge) of RDT trees that share the same sample in the same PreDefined sample Set (PDS).
These files are generated by `se3solver.py solve --samset` or `se3solver.py solve --samset2`

Note:
    This application does NOT (and ARE NOT ABLE TO) check the same PDS is used.
    User is responsible to guarantee this.
'''

import argparse
from scipy.io import loadmat
import scipy.sparse as sparse

def print_edge(args):
    cl = []
    for fn in args.files:
        cl.append(loadmat(fn)['C'])
    mc = sparse.vstack(cl, format='csc')
    cws = mc.sum(axis=0)
    #print(cws.shape)
    for i in range(cws.shape[1]):
        s = cws[0,i]
        if s < 2:
            continue
        rows,_ = mc[:,i].nonzero()
        for r,c in zip(rows[:-1], rows[1:]):
            print("{},{}".format(r,c))

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('files', help='ssc-*.mat file', nargs='+')
    args = parser.parse_args()
    print_edge(args)

if __name__ == '__main__':
    main()
